"""Native tool registry objects for Deepmate."""

from deepmate.tools.registry import (
    NativeTool,
    NativeToolHandler,
    NativeToolRegistry,
    NativeToolResult,
)
from deepmate.tools.browser import (
    BROWSER_CLICK_TOOL_NAME,
    BROWSER_CLOSE_TOOL_NAME,
    BROWSER_FILL_TOOL_NAME,
    BROWSER_OPEN_TOOL_NAME,
    BROWSER_SCREENSHOT_TOOL_NAME,
    BROWSER_SNAPSHOT_TOOL_NAME,
    BROWSER_STATUS_TOOL_NAME,
    BROWSER_WAIT_TOOL_NAME,
    INSTALL_BROWSER_BACKEND_TOOL_NAME,
    LOAD_BROWSER_TOOLS_NAME,
    AgentBrowserBackend,
    BrowserCommandResult,
    BrowserInstallResult,
    BrowserInstallStep,
    BrowserValidationResult,
    BrowserValidationStep,
    browser_loader_tools,
    browser_tools,
    format_browser_install_result,
    format_browser_validation_result,
    install_browser_backend,
    validate_browser_backend,
)
from deepmate.tools.computer import (
    COMPUTER_CLICK_TOOL_NAME,
    COMPUTER_KEY_TOOL_NAME,
    COMPUTER_OPEN_TOOL_NAME,
    COMPUTER_SCREENSHOT_TOOL_NAME,
    COMPUTER_SNAPSHOT_TOOL_NAME,
    COMPUTER_STATUS_TOOL_NAME,
    COMPUTER_TOOL_NAMES,
    COMPUTER_TYPE_TOOL_NAME,
    COMPUTER_WAIT_TOOL_NAME,
    ComputerUseState,
    computer_tools,
)
from deepmate.tools.artifacts import REVIEW_ARTIFACT_TOOL_NAME, workspace_artifact_tools
from deepmate.tools.filesystem import workspace_filesystem_tools
from deepmate.tools.diagrams import RENDER_TECH_DIAGRAM_TOOL_NAME, workspace_diagram_tools
from deepmate.tools.documents import workspace_document_tools
from deepmate.tools.lsp import (
    LSP_DEFINITION_TOOL_NAME,
    LSP_HOVER_TOOL_NAME,
    LSP_REFERENCES_TOOL_NAME,
    workspace_lsp_tools,
)
from deepmate.tools.mcp_loader import (
    LOAD_MCP_TOOL_NAME,
    SEARCH_MCP_TOOLS_NAME,
    mcp_loader_tools,
)
from deepmate.tools.reports import workspace_report_tools
from deepmate.tools.search import workspace_search_tools
from deepmate.tools.shell import RUN_SHELL_COMMAND_TOOL_NAME, shell_tools
from deepmate.tools.skill_installer import (
    INSPECT_SKILL_SOURCE_TOOL_NAME,
    INSTALL_SKILL_FROM_REQUEST_TOOL_NAME,
    INSTALL_SKILL_BUNDLE_TOOL_NAME,
    INSTALL_SKILL_TOOL_NAME,
    LOAD_SKILL_INSTALLER_TOOLS_NAME,
    PLAN_SKILL_SETUP_TOOL_NAME,
    RUN_SKILL_SETUP_TOOL_NAME,
    VERIFY_SKILL_INSTALL_TOOL_NAME,
    skill_installer_tools,
)
from deepmate.tools.skill_loader import LOAD_SKILL_TOOL_NAME, skill_loader_tools
from deepmate.tools.tool_output import RETRIEVE_TOOL_OUTPUT_NAME, tool_output_tools
from deepmate.tools.web import web_research_tools

__all__ = [
    "BROWSER_CLICK_TOOL_NAME",
    "BROWSER_CLOSE_TOOL_NAME",
    "BROWSER_FILL_TOOL_NAME",
    "BROWSER_OPEN_TOOL_NAME",
    "BROWSER_SCREENSHOT_TOOL_NAME",
    "BROWSER_SNAPSHOT_TOOL_NAME",
    "BROWSER_STATUS_TOOL_NAME",
    "BROWSER_WAIT_TOOL_NAME",
    "INSTALL_BROWSER_BACKEND_TOOL_NAME",
    "LOAD_BROWSER_TOOLS_NAME",
    "AgentBrowserBackend",
    "BrowserCommandResult",
    "BrowserInstallResult",
    "BrowserInstallStep",
    "BrowserValidationResult",
    "BrowserValidationStep",
    "COMPUTER_SCREENSHOT_TOOL_NAME",
    "COMPUTER_SNAPSHOT_TOOL_NAME",
    "COMPUTER_STATUS_TOOL_NAME",
    "COMPUTER_CLICK_TOOL_NAME",
    "COMPUTER_KEY_TOOL_NAME",
    "COMPUTER_OPEN_TOOL_NAME",
    "COMPUTER_TOOL_NAMES",
    "COMPUTER_TYPE_TOOL_NAME",
    "COMPUTER_WAIT_TOOL_NAME",
    "ComputerUseState",
    "INSPECT_SKILL_SOURCE_TOOL_NAME",
    "INSTALL_SKILL_FROM_REQUEST_TOOL_NAME",
    "INSTALL_SKILL_BUNDLE_TOOL_NAME",
    "INSTALL_SKILL_TOOL_NAME",
    "LOAD_SKILL_TOOL_NAME",
    "LOAD_SKILL_INSTALLER_TOOLS_NAME",
    "LOAD_MCP_TOOL_NAME",
    "LSP_DEFINITION_TOOL_NAME",
    "LSP_HOVER_TOOL_NAME",
    "LSP_REFERENCES_TOOL_NAME",
    "NativeTool",
    "NativeToolHandler",
    "NativeToolRegistry",
    "NativeToolResult",
    "PLAN_SKILL_SETUP_TOOL_NAME",
    "RENDER_TECH_DIAGRAM_TOOL_NAME",
    "REVIEW_ARTIFACT_TOOL_NAME",
    "RETRIEVE_TOOL_OUTPUT_NAME",
    "RUN_SHELL_COMMAND_TOOL_NAME",
    "RUN_SKILL_SETUP_TOOL_NAME",
    "SEARCH_MCP_TOOLS_NAME",
    "VERIFY_SKILL_INSTALL_TOOL_NAME",
    "browser_loader_tools",
    "browser_tools",
    "computer_tools",
    "format_browser_install_result",
    "format_browser_validation_result",
    "install_browser_backend",
    "mcp_loader_tools",
    "shell_tools",
    "skill_installer_tools",
    "skill_loader_tools",
    "tool_output_tools",
    "validate_browser_backend",
    "web_research_tools",
    "workspace_artifact_tools",
    "workspace_diagram_tools",
    "workspace_document_tools",
    "workspace_filesystem_tools",
    "workspace_lsp_tools",
    "workspace_report_tools",
    "workspace_search_tools",
]
